[package]

name = "EVImproved-rs"
version = "0.0.1"
authors = ["Antti KerÃ¤nen <detegr@gmail.com>"]

[dependencies.url]
git = "https://github.com/servo/rust-url"

[dependencies]
rustc-serialize = "0.1.5"
